spring:
  profiles:
    active: dev 
  application:
    name: easyhome
  kafka:
    consumer:
      group-id: easyhome-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      database: 1
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /doc.html
  packages-to-scan: com.coooolfan.easyhome.pojo,com.coooolfan.easyhome.controller
llm:
  api-url: https://api.deepseek.com/chat/completions
  model: deepseek-chat
embed:
  #  同一环境确保模型一致，确保返回1536维向量
  #  OPENAI兼容端点 类似于
  api-url: https://api.etak.cn/v1/embeddings
  model: text-embedding-3-small
aliyun:
  oss: