spring:
  application:
    name: easyhome
  datasource:
    url: jdbc:postgresql://localhost:5432/easyhome
    username: easyhome
    password: easyhome
    type: com.alibaba.druid.pool.DruidDataSource
  ai:
    deepseek:
      api-key:
server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /test
  packages-to-scan: com.coooolfan.easyhome.pojo,com.coooolfan.easyhome.controller
llm:
  api-url: 写你自己的API地址
  api-key: 写你自己的API Key
  model: 写你自己的模型名称
