spring:
  application:
    name: easyhome
  datasource:
    url: jdbc:postgresql://localhost:5432/easyhome
    username: easyhome
    password: easyhome
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /doc.html
  packages-to-scan: com.coooolfan.easyhome.pojo,com.coooolfan.easyhome.controller
llm:
  api-url: https://api.deepseek.com/chat/completions
  api-key: sk-36560f3847b44472862877c04f6306d3
  model: deepseek-chat
embed:
#  同一环境确保模型一致，确保返回1536维向量
#  OPENAI兼容端点 类似于
  api-url: https://api.openai.com/v1/embeddings
  api-key:
  model: text-embedding-3-small

